apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: datacompass-frontend-production

namespace: production

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

images:
  - name: datacompass-frontend
    newTag: v1.0.0

commonLabels:
  environment: production

configMapGenerator:
  - name: datacompass-frontend-config
    behavior: merge
    literals:
      - api-url=http://whatsapp-analytics-api-service.production.svc.cluster.local

