apiVersion: apps/v1
kind: Deployment
metadata:
  name: datacompass-dashboard
  labels:
    app: datacompass-dashboard
    component: frontend
    tier: presentation
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: datacompass-dashboard
      component: frontend
  template:
    metadata:
      labels:
        app: datacompass-dashboard
        component: frontend
        tier: presentation
        version: v1
    spec:
      containers:
      - name: dashboard-frontend
        image: IMAGE_TAG_PLACEHOLDER
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: datacompass-dashboard-config
              key: external-api-url
        - name: VITE_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: datacompass-dashboard-config
              key: api-base-url
        - name: VITE_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: datacompass-dashboard-config
              key: dashboard-url
        - name: VITE_APP_NAME
          valueFrom:
            configMapKeyRef:
              name: datacompass-dashboard-config
              key: app-name
        - name: VITE_APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: datacompass-dashboard-config
              key: app-version
        - name: VITE_DOMAIN_NAME
          valueFrom:
            configMapKeyRef:
              name: datacompass-dashboard-config
              key: domain-name
        - name: VITE_API_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: datacompass-dashboard-config
              key: api-domain
        - name: VITE_DASHBOARD_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: datacompass-dashboard-config
              key: dashboard-domain
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
      volumes:
      - name: tmp
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      securityContext:
        fsGroup: 1001
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

