apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: datacompass-frontend-base

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app: datacompass-frontend
  component: frontend

images:
  - name: IMAGE_TAG_PLACEHOLDER
    newName: datacompass-frontend
    newTag: latest

namespace: default

