apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: datacompass-unified
  namespace: default

resources:
  # Frontend resources
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  
  # API resources (from dataCompass1.0)
  - ../../../dataCompass1.0/k8s/base/configmap.yaml
  - ../../../dataCompass1.0/k8s/base/deployment.yaml
  - ../../../dataCompass1.0/k8s/base/service.yaml
  - ../../../dataCompass1.0/k8s/base/hpa.yaml
  - ../../../dataCompass1.0/k8s/base/secrets.yaml
  
  # Unified ingress
  - ingress-unified.yaml

commonLabels:
  project: datacompass
  environment: production

namePrefix: datacompass-

images:
  - name: IMAGE_TAG_PLACEHOLDER
    newName: datacompass-frontend
    newTag: latest
  - name: IMAGE_TAG_PLACEHOLDER
    newName: datacompass-api
    newTag: latest

replicas:
  - name: datacompass-frontend
    count: 2
  - name: whatsapp-analytics-api
    count: 3

configMapGenerator:
  - name: unified-config
    literals:
      - ENVIRONMENT=production
      - CLUSTER_NAME=datacompass-production
      - DOMAIN_NAME=ultimatesystems.io
      - API_DOMAIN=api.ultimatesystems.io
      - FRONTEND_DOMAIN=ultimatesystems.io
      - ADMIN_DOMAIN=administrativo.ultimatesystems.io
      - DASHBOARD_DOMAIN=dashboard.ultimatesystems.io

