apiVersion: v1
kind: Service
metadata:
  name: datacompass-frontend-service
  labels:
    app: datacompass-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: datacompass-frontend

