apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datacompass-frontend-ingress
spec:
  rules:
  - host: staging-datacompass.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: datacompass-frontend-service
            port:
              number: 80

