apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: datacompass-frontend-staging

namespace: staging

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

images:
  - name: datacompass-frontend
    newTag: staging

commonLabels:
  environment: staging

configMapGenerator:
  - name: datacompass-frontend-config
    behavior: merge
    literals:
      - api-url=http://whatsapp-analytics-api-service.staging.svc.cluster.local

